name: "🔥 Release Production Tag"

on:
  push:
    branches: [ "main" ]
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  CLUSTER_NAME: https://tcc-01.th1.proen.cloud/api/

jobs:
  checkout_image:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.get_pre_image_tag.outputs.previous_image_tag }}
    environment: prod
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Clone nonprod repository
        uses: actions/checkout@v3
        with:
          repository: 'the-cloud-camp/tcc-k8s-config-nonprd'
          token: ${{ secrets.GH_PAT }}  # Use your PAT for private repositories
          path: 'tcc-k8s-config-nonprd'
          ref: main

      - name: Get Image Tag
        id: get_pre_image_tag
        working-directory: tcc-k8s-config-nonprd
        run: |
          PREVIOUS_TAG=$(yq e '.spec.template.spec.containers[0].image' kai-nuxtjs/deployment.yaml | cut -d ':' -f 2)
          echo "$PREVIOUS_TAG"
          echo "previous_image_tag=$PREVIOUS_TAG" >> "$GITHUB_OUTPUT"
          
  tagging:
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout tag on repository
        uses: actions/checkout@v3

      - name: Cat version
        run: |-
          cat package.json | jq -r .version
          echo "IMAGE_TAG=$(cat package.json | jq -r .version)" >> $GITHUB_ENV

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Retag Image
        run: |
          original_tag=${{ needs.checkout_image.outputs.previous_image_tag }}
          source $GITHUB_ENV
          new_tag=$IMAGE_TAG  # Define your new tag here

          # Assuming you are using Docker
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$original_tag
          docker tag  ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$original_tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$new_tag
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$new_tag